# Generated by Django 5.2.1 on 2025-05-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reserva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
